routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/reglages', [App\Http\Controllers\ReglagesController::class, 'index'])->name('reglages')->middleware('admin');
Route::get('/articles', [App\Http\Controllers\ArticlePageController::class, 'index'])->name('articles');
Route::get('/services/{id}', [App\Http\Controllers\ServicePageController::class, 'index'])->name('services');
Route::get('/communication', [App\Http\Controllers\CommunicationPageController::class, 'index'])->name('communication');
Route::get('/panier', [App\Http\Controllers\PanierController::class, 'index'])->name('panier')->middleware('auth');
Route::get('/panier/ajout-article/{article}', [App\Http\Controllers\PanierController::class, 'ajouterArticle'])->name('panier.ajouterArticle')->middleware('auth');
Route::get('/panier/ajout-service/{service}/{vehicule}', [App\Http\Controllers\PanierController::class, 'ajouterService'])->name('panier.ajouterService')->middleware('auth');
Route::get('/panier/supprimer/{itemId}', [App\Http\Controllers\PanierController::class, 'destroy'])->name('panier.destroy')->middleware('auth');

Route::resource('article', 'App\Http\Controllers\ArticleController')->middleware('admin');
Route::resource('service', 'App\Http\Controllers\ServiceController')->middleware('admin');
Route::resource('notification', 'App\Http\Controllers\NotificationController')->middleware('admin');
Route::resource('historiqueVentes', 'App\Http\Controllers\HistoriqueVentesController')->middleware('admin');
Route::resource('vehicule', 'App\Http\Controllers\VehiculeController')->middleware('admin');

app/Http/Controllers/ServicePageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Service;
use App\Models\ServiceVehicule;
use App\Models\Vehicule;
use Illuminate\Http\Request;

/**
 * Class ServicePageController
 * @package App\Http\Controllers
 *
 * Page qui affiche les services offerts selon le type de véhicule sélectionné
 */
class ServicePageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index($id)
    {
        if ($id!=0) {
            $v = Vehicule::findOrFail($id);
        } else {
            $v = $id;
        }
        $services = Service::all();
        $vehicules = Vehicule::all();
        return view('servicePage.index', compact('services', 'vehicules', 'v'));
    }
}

resources/views/servicePage/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <section class="section-padding">
            <div class="jumbotron" style="padding-top: 15px; background-color: #50B3E5">
                <div class="d-flex justify-content-between">
                    <h1>Services</h1>
                    @if (session('success'))
                        <div class="alert alert-success text-sm-center w-25 p-3 p-3 mb-2 bg-secondary text-white" role="alert">
                            {{ session('success') }}
                            <button class="btn-info rounded-lg" onClick="window.location.reload();"><img src="/Images/reload.svg"></button>
                        </div>
                    @endif
                    <div class="dropdown form-group">
                        <select class="form-control btn-dark" type="dropdown-toggle" id="id" name="id"
                                onchange="top.location.href = this.options[this.selectedIndex].value">
                            @if ($v == '0')
                                <option disabled selected value="">Sélectionner type de vehicule</option>
                            @else
                                <option>{{ $v->type }}</option>
                            @endif
                            @foreach($vehicules as $vehicule)
                                @if ($vehicule != $v)
                                <option class="id" value="{{ route('services', ['id' => $vehicule->id]) }}">
                                    {{ $vehicule->type }}
                                </option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    @auth
                        @if (Auth::user()->role==1)
                            <a href="{{ route('service.create') }}" class="btn btn-primary text-justify">Ajouter un service</a>
                        @endif
                    @endauth
                </div>
                @foreach($services as $service)
                    <div class="card mt-3" style="background-color: #C4E0FF">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">

                                <h4 class="card-title">{{ $service->nom }}</h4>
                                @if ($v != '0')
                                    <h3 class="service-prix">{{ $service->prix + $v->prix }}$</h3>
                                @endif
                            </div>
                            <p class="card-text">{{ $service->description }}</p>
                            <img src="{{asset('/Images/'.$service->image)}}" class="img-thumbnail" alt="logo" style="width: 10%;">
                            <div class="text-right">
                                @auth
                                    @if (Auth::user()->role == 1)
                                        <a href="{{ route('service.edit', [$service->id]) }}" class="card-link pr-3">Modifier</a>
                                    @endif
                                @endauth
                                @if (auth()->check() and $v != '0')
                                    <a href="{{ route('panier.ajouterService', [$service->id, $v->id]) }}" class="btn btn-dark">Ajouter au panier</a>
                                @endif
                            </div>

                        </div>

                    </div>
                @endforeach
            </div>
        </section>
    </div>

@stop