routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/reglages', [App\Http\Controllers\ReglagesController::class, 'index'])->name('reglages')->middleware('admin');
Route::get('/articles', [App\Http\Controllers\ArticlePageController::class, 'index'])->name('articles');
Route::get('/services/{id}', [App\Http\Controllers\ServicePageController::class, 'index'])->name('services');
Route::get('/communication', [App\Http\Controllers\CommunicationPageController::class, 'index'])->name('communication');
Route::get('/panier', [App\Http\Controllers\PanierController::class, 'index'])->name('panier')->middleware('auth');
Route::get('/panier/ajout-article/{article}', [App\Http\Controllers\PanierController::class, 'ajouterArticle'])->name('panier.ajouterArticle')->middleware('auth');
Route::get('/panier/ajout-service/{service}/{vehicule}', [App\Http\Controllers\PanierController::class, 'ajouterService'])->name('panier.ajouterService')->middleware('auth');
Route::get('/panier/supprimer/{itemId}', [App\Http\Controllers\PanierController::class, 'destroy'])->name('panier.destroy')->middleware('auth');

Route::resource('article', 'App\Http\Controllers\ArticleController')->middleware('admin');
Route::resource('service', 'App\Http\Controllers\ServiceController')->middleware('admin');
Route::resource('notification', 'App\Http\Controllers\NotificationController')->middleware('admin');
Route::resource('historiqueVentes', 'App\Http\Controllers\HistoriqueVentesController')->middleware('admin');
Route::resource('vehicule', 'App\Http\Controllers\VehiculeController')->middleware('admin');

app/Http/Controllers/ReglagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ReglagesController extends Controller
{
    public function index()
    {
        return view('reglages/reglages');
    }
}

resources/views/reglages/reglages.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <section class="section-padding">
            <div class="jumbotron" style="padding-top: 15px">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Réglages</h2>
                        <div class="container pt-2">
                            <a href="{{ route('article.index') }}" style="color: #1a202c">
                                <h3>Articles</h3>
                            </a>
                            <a href="{{ route('notification.index') }}" style="color: #1a202c">
                                <h3>Notifications</h3>
                            </a>
                            <a href="{{ route('service.index') }}" style="color: #1a202c">
                                <h3>Services</h3>
                            </a>
                            <a href="{{ route('vehicule.index') }}" style="color: #1a202c">
                                <h3>Vehicules</h3>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@stop